#!/usr/bin/env python3
"""gen_readme.py — Generate README.md from op_registry.json."""

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def build_readme(registry: dict, pages_url: str) -> str:
    summary = registry.get("summary", {})
    ops = registry.get("ops", {})
    generated = registry.get("generated_at", "unknown")

    total = summary.get("total_ops", 0)
    impl = summary.get("impl_ops", 0)
    tested = summary.get("tested_ops", 0)
    benched = summary.get("benched_ops", 0)
    done = summary.get("done_ops", 0)

    # Status counts
    ts_counts = {"passed": 0, "failed": 0, "missing": 0}
    bs_counts = {"qualified": 0, "passed": 0, "underperforming": 0, "failed": 0, "missing": 0}
    for op in ops.values():
        ts = (op.get("test_status") or {}).get("status", "missing")
        bs = (op.get("bench_status") or {}).get("status", "missing")
        ts_counts[ts] = ts_counts.get(ts, 0) + 1
        bs_counts[bs] = bs_counts.get(bs, 0) + 1

    bench_ok = bs_counts.get("qualified", 0) + bs_counts.get("passed", 0)

    lines = [
        "# TileOPs Nightly Report",
        "",
        f"> Auto-generated from [`op_registry.json`](scripts/op_registry.json) | "
        f"Last updated: {generated}",
        "",
        f"[View full HTML report]({pages_url})",
        "",
        "## Overall Progress",
        "",
        f"| Total | Implemented | Test Passed | Bench Passed | Done |",
        f"|:-----:|:-----------:|:-----------:|:------------:|:----:|",
        f"| {total} | {impl} | {tested} | {benched} | **{done}** ({done*100//total if total else 0}%) |",
        "",
        "### Test Status",
        "",
        f"| Passed | Failed | Missing |",
        f"|:------:|:------:|:-------:|",
        f"| {ts_counts['passed']} | {ts_counts['failed']} | {ts_counts['missing']} |",
        "",
        "### Benchmark Status",
        "",
        f"| Qualified | Passed (no ratio) | Underperforming | Failed | Missing |",
        f"|:---------:|:-----------------:|:---------------:|:------:|:-------:|",
        f"| {bs_counts.get('qualified',0)} | {bs_counts.get('passed',0)} | {bs_counts.get('underperforming',0)} | {bs_counts.get('failed',0)} | {bs_counts.get('missing',0)} |",
        "",
        "## Category Progress",
        "",
    ]

    for cat in summary.get("categories", []):
        name = cat["name"]
        t = cat["total_ops"]
        im = cat["impl_ops"]
        te = cat.get("tested_ops", 0)
        be = cat.get("benched_ops", 0)
        d = cat["done_ops"]
        impl_bar = _progress_bar(im, t)
        test_bar = _progress_bar(te, t)
        bench_bar = _progress_bar(be, t)
        lines.append(f"### {name}")
        lines.append("")
        lines.append(f"| | Progress | Count |")
        lines.append(f"|:--|:---------|------:|")
        lines.append(f"| Impl | {impl_bar} | {im}/{t} |")
        lines.append(f"| Test | {test_bar} | {te}/{t} |")
        lines.append(f"| Bench | {bench_bar} | {be}/{t} |")
        lines.append(f"| **Done** | | **{d}/{t}** |")
        lines.append("")

        # Per-op table
        lines.append("<details>")
        lines.append(f"<summary>Operators ({d}/{t} done)</summary>")
        lines.append("")
        lines.append("| Operator | Impl | Test | Bench |")
        lines.append("|:---------|:----:|:----:|:-----:|")
        for op in cat.get("ops", []):
            op_name = op["name"]
            impl_s = "Y" if op.get("implemented") else "-"
            test_s = "Y" if op.get("tested") else ("FAIL" if op.get("test_failed") else "-")
            bench_s = "Y" if op.get("bench_ok") is True else ("FAIL" if op.get("bench_ok") is False else "-")
            lines.append(f"| {op_name} | {impl_s} | {test_s} | {bench_s} |")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    lines += [
        "---",
        "",
        f"*Generated by [TileOPs Report]({pages_url}) pipeline*",
    ]

    return "\n".join(lines)


def _progress_bar(count: int, total: int, width: int = 20) -> str:
    """Generate a text progress bar."""
    if total == 0:
        return "`" + "." * width + "`"
    filled = round(count / total * width)
    bar = "#" * filled + "." * (width - filled)
    pct = count * 100 // total
    return f"`{bar}` {pct}%"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate README.md from registry")
    parser.add_argument("--registry", required=True, help="op_registry.json path")
    parser.add_argument("--output", default="README.md", help="Output path")
    parser.add_argument("--pages-url", default="https://superanggao.github.io/TileOPs-report/nightly/")
    args = parser.parse_args()

    registry = json.loads(Path(args.registry).read_text())
    readme = build_readme(registry, args.pages_url)
    Path(args.output).write_text(readme)
    print(f"README written: {args.output}")


if __name__ == "__main__":
    main()
